spring.application.name=garden

# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/garden_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/changelog.xml
spring.liquibase.enabled=true
spring.liquibase.contexts=development,production
spring.liquibase.default-schema=bio_garden
spring.liquibase.database-change-log-lock-table=liquibase_changelog_lock
spring.liquibase.database-change-log-table=liquibase_changelog

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Logging
logging.level.liquibase=DEBUG

# HTTPS / SSL
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=${SSL_KEY_STORE_PATH:classpath:keystore.p12}
server.ssl.key-store-password=${SSL_KEY_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=garden

# HTTP -> HTTPS redirect
server.http.port=8080

