spring.application.name=garden

# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/garden_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/changelog.xml
spring.liquibase.enabled=true
spring.liquibase.contexts=development,production
spring.liquibase.default-schema=bio_garden
spring.liquibase.drop-first=false

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=bio_garden

# Logging
logging.level.liquibase=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.boot.autoconfigure=DEBUG

